spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: {DB_URL_PROD}
    hikari:
      maximum-pool-size: 1
  jpa:
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: true
    hibernate:
      ddl-auto: update