spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vitalcare_db
    username: ${DB_USER_PROD}
    password: ${DB_PASSWORD_PROD}
    hikari:
      maximum-pool-size: 1
  jpa:
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: true
    hibernate:
      ddl-auto: update